"""Comments added

Revision ID: 82937ff98b59
Revises: c92e1331862a
Create Date: 2020-11-05 13:29:04.077875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82937ff98b59'
down_revision = 'c92e1331862a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comment_user_id'), 'comment', ['user_id'], unique=False)
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_index(op.f('ix_comment_user_id'), table_name='comment')
    op.drop_column('comment', 'user_id')
    # ### end Alembic commands ###
